### ISSUE TITLE
Exception while executing _shutdown

### ISSUE THREAD

**Issue by ruizhang0101** [MITIBMxGraph/SALIENT_artifact#1]
I am running the _run_all_single_gpu_experiments.sh_

However I found that **after each task**, to be specific, _$SCRIPT_DIR/performance_breakdown_salient.sh \`basename $FILE\`_ or _$SCRIPT_DIR/performance_breakdown_pyg.sh \`basename $FILE\`_. The procedure will stuck. 

The traceback shows that there is an exception while excuting the _lock.acquire()_ in __shutdown_ of module threading.

> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/threading.py", line 1428, in _shutdown
>     lock.acquire()

Although the exception can be ignored, I am still wondering the solution.

**Comment by timkaler** [comment]
I do not seem to be able to reproduce this error/exception when starting with a fresh clone of the SALIENT_artifact repository. As far as I can tell, from my test on AWS g5.8xlarge instances, there are no errors/exceptions being reported. 

Am I correct in thinking that, in your environment, the scripts are completing correctly (e.g., run_all_single_gpu_experiments.sh is running all of the experiments to completion), but there are errors/exceptions reported in the output? 

Could you provide some more details about your environment (e.g., docker, amazon, etc.), and whether you are running from a fresh clone of SALIENT_artifact?

**Comment by ruizhang0101** [comment]
> I do not seem to be able to reproduce this error/exception when starting with a fresh clone of the SALIENT_artifact repository. As far as I can tell, from my test on AWS g5.8xlarge instances, there are no errors/exceptions being reported.
> 
> Am I correct in thinking that, in your environment, the scripts are completing correctly (e.g., run_all_single_gpu_experiments.sh is running all of the experiments to completion), but there are errors/exceptions reported in the output?
> 
> Could you provide some more details about your environment (e.g., docker, amazon, etc.), and whether you are running from a fresh clone of SALIENT_artifact?


Thanks a lot for your reply.

It seems that there were some steps I missed while installing. I reinstalled it and the exception is gone.

Thank you for your precious time.
